### PR TITLE
Fixes #3

### LINKED ISSUE #3: Refactor notifications endpoints to activity endpoints
`GET /activity`
`POST /activity`
`GET /activity/{id}`
`PATCH /activity/{id}`
`DELETE /activity/{id}`

Candidate activity resource:

``` JSON
"activity": {
  "id": {
    "type": "string"
  },
  "link": {
    "$ref": "link"
  },
  "regarding": {
    "$ref": "link"
  },
  "action": {
    "type": "string"
  },
  "actionTime": {
    "type": "string", 
    "format": "date-time"
  },
  "username": {
    "type": "string"
  }
}
```

### PR DESCRIPTION
**Pull request by chriscorcimiglia**
1. Renamed notification schemas and endpoints to (notification/notifications --> activity)
2. Refactored schemas and endpoints to align with our current API designs and to meet requirements from #3

### CODE REVIEW

**Comment by dschrimpsher** [comment]
I am not sure what username means in BSIM context.  Should it be API or BSIM or blank.

**Comment by dschrimpsher** [comment]
Keep in mind that so far nearly all the activities I have seen are automatically generated and never created or updated by human hands.

**Comment by dschrimpsher** [comment]
Aside from that question i am fine with it.

**Comment by chriscorcimiglia** [comment]
I described username as:

> The username of the user who performed the action. This may be an API user and not a specific app user. The level of granularity is left to the creator of the activity.

This would mean that if an App was logging the activity, it would populate the actual username of the user who performed the action on the resource (maybe chriscorcimiglia). OR if an API was logging the activity, it would populate username with the API user who performed the action on the resource.

**Comment by chriscorcimiglia** [comment]
@dschrimpsher maybe a different name for username would help?

**Comment by chriscorcimiglia** [comment]
@dschrimpsher I was also wondering if you think `resource` would be a better name that `regarding`? Or maybe `affectedResource`?

**Comment by dschrimpsher** [comment]
resource is too vague.  I can live with affectedResource but frankly I like regarding better than either.

**Comment by chriscorcimiglia** [comment]
@dschrimpsher I agree that activity would almost always be auto-generated by either and App or an API implementation (like BSIM).

**Comment by chriscorcimiglia** [comment]
Ok, we'll stick with `regarding`. I can grow to like it.

**Comment by chriscorcimiglia** [comment]
@donricouga, @dschrimpsher and I are trying to figure out how `username` is going to be populated when an `activity` is generated. Can you help us?

**Comment by dschrimpsher** [comment]
Should username be users or orgs in the API.

**Comment by donricouga** [comment]
Not sure.  Mark says Orgs.

**Comment by chriscorcimiglia** [comment]
What I'm saying @dschrimpsher is that `username` could be populated with something like an _api-username_  I'm not saying that everything has to be down the the user level. I'm saying that `username` can be overloaded as its description states, which is why I was wondering if we should rename `username`.

**Comment by dschrimpsher** [comment]
Also (and I just thought of this)   So SAR Details 
Alpha Creates SAR   ----remote Post to Beta -->  Beta Create Sar and Notificaiton (who is user Bob@Alpha?)
Beta Creates SAR Details ----- remote POST to Alpha--> Alpha adds Details and Notification (who is user Frank @Beta?)

**Comment by dschrimpsher** [comment]
In other words are we sharing our user base?

**Comment by dschrimpsher** [comment]
So username could be responsibleParty or some such thing

**Comment by chriscorcimiglia** [comment]
`responsibleParty` might work @dschrimpsher Remember this is a **common** definition which is meant to be reusable, so we want to be able to log an activity. Let me try `responsibleParty` on for size. That name along with a solid description might work well.

**Comment by chriscorcimiglia** [comment]
@donricouga I think keys being issued to organizations is appropriate. We'll just need a way for determining what organization has been issued what keys (a look-up for things like BSIM).

**Comment by dschrimpsher** [comment]
How this sound       [https://github.com/cablelabs/bsim/issues/87]

**Comment by donricouga** [comment]
there is mapping in database already. See this page https://sapoc.herokuapp.com/security/

**Comment by dschrimpsher** [comment]
Well Okay than I will update it.

**Comment by chriscorcimiglia** [comment]
`responsibleParty`:

> A reference to the party that performed the action on the resource. This could be the username of the User who performed the action. This could also be a reference to the party (e.g. Organization) that accessed the API endpoint to perform the action on the resource.

**Comment by dschrimpsher** [comment]
Works for me

**Comment by chriscorcimiglia** [comment]
Cool. I'll make the changes.

**Comment by dschrimpsher** [comment]
@donricouga  hows that?  :-) [https://github.com/cablelabs/bsim/issues/87]

**Comment by chriscorcimiglia** [comment]
How about that @dschrimpsher? Are you good now too @donricouga?

**Comment by dschrimpsher** [comment]
Ship it

**Pull request merged**
