### PR TITLE
fixed #1 Organization Schema

### LINKED ISSUE #1: Create Organization Schema
Create a full Organization Schema including 
1) Everything in Org Summary
2) BSIM/API URL

See [BSIM Issue 53](https://github.com/cablelabs/bsim/issues/53)  & [BSIM Issue 50](https://github.com/cablelabs/bsim/issues/50)

### PR DESCRIPTION
**Pull request by dschrimpsher**
1) Added Schema for Organization including an array of API Urls
2) Added Schema for OrgannizationList
3) Added organization and organization-id endpoints.

### CODE REVIEW

**Comment by donricouga** [comment]
looks fine to me. ship it

**Comment by chriscorcimiglia** [comment]
@dschrimpsher responses should match what is laid out here: https://github.com/cablelabs/serviceability/issues/28

Same for parameters (see the last comment): https://github.com/cablelabs/serviceability/issues/26

All the serviceability endpoints should be prett good examples now.

**Comment by chriscorcimiglia** [comment]
I plan to document all that in a better place than in issues. Just what I have for now.

**Comment by dschrimpsher** [comment]
I don't mind adding PUT and Delete but I would point out that neither is defined in Serviceability endpoints .

**Comment by dschrimpsher** [comment]
@chriscorcimiglia updated.

**Comment by chriscorcimiglia** [comment]
@dschrimpsher I was talking about cleaning up the parameters and responses for the operations you had defined, not about adding PUT and DELETE. Looks good though.

**Comment by dschrimpsher** [comment]
Oh, woops.  Well no harm done since BSIm supports all that stuff anyway.

**Pull request merged**
